[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_OPTIONS = "--max_old_space_size=8192"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
  publish = "dist"